### ISSUE TITLE
Alternative to bittorrent

### ISSUE THREAD

**Issue by dswd** [GLab/ToMaTo#1110]
We need a way to synchronize the templates and user content between the hosts. The following features are important in this regard:
* Download from multiple sources with preference for those which are close by
* Continuous offering of files for other hosts
* Selective download of single files
* No access to shared content for outsiders
* Controllable by backend
* Support for on-demand user content

### Bittorrent
The backend runs a tracker whose URL is embedded in all torrent files. Those torrent files are distributed to the hosts which can then contact the tracker and be introduced to other hostmanagers.
* Multiple sources: supported :white_check_mark: 
* Continuous offering: supported :white_check_mark: 
* Selective download: yes, but every file requires its own torrent file :warning: 
* Restricted access: possible by hacks :warning: 
* Controllable by backend: by adding torrent files to the folder, indirect :warning:
* On-demand user content: torrent files have to be created manually, no notification when done :no_entry:  

### Aria2 + Webserver + Metalink
Each hostmanager runs a small webserver and serves its template folder under a secret path (listing is disabled of course). The backend collects all links to those templates and distributes them in metalink format to all hosts. The hosts use those metalink files to download the file to their template folder.
* Multiple sources: supported but only when finished (metalink) :warning: 
* Continuous offering: supported (webserver) :white_check_mark: 
* Selective download: supported :white_check_mark: : 
* Restricted access: possible by security tokens but complicated :warning: 
* Controllable by backend: direct control by running aria2 :white_check_mark:
* On-demand user content: metalink and aria2 support many protocols and aria2 exits when done :white_check_mark:  

### Amule
All hosts are running an amule daemon and offer their template folder. When needed, the hosts download templates from the emule network.
* Multiple sources: supported :white_check_mark: 
* Continuous offering: supported :white_check_mark: 
* Selective download: supported :white_check_mark: 
* Restricted access: problematic :no_entry: 
* Controllable by backend: using the cmd client :white_check_mark: 
* On-demand user content: users must run an emule client, no notification when done :no_entry:

**Comment by swuest** [comment]
Syncthing:

The backend and the hostmanagers have to run a syncthing client and have to be connected to each other. The files will be synchronized automatically and the folders can be fully configured for individual purposes like selective download etc. If we want to be fully indipendent of the syncthing network we have to run our own discovery server: http://docs.syncthing.net/users/discosrv.html

https://syncthing.net/

* Multiple sources: supported http://docs.syncthing.net/users/faq.html#what-things-are-synced
* Continuous offering: supported
* Selective download of single files: supported
* Restricted access: supported
* Controllable by backend: cmd client -> supported
* On-demand user content: (not sure)

**Comment by dswd** [comment]
My current preference is the **Aria2 + Webserver + Metalink** option as it seems to solve best the dual goals of passive continuous offering and active on-demand fetching.

**Comment by dswd** [comment]
Superseded by #1316
