### ISSUE TITLE
Global config file for all backend services and webfrontend

### ISSUE THREAD

**Issue by t-gerhard** [GLab/ToMaTo#1161]
This global file is then provided to all modules.

It is written so that each service can be configured, and shared preferences are configured for all services with the same setting.
This one central file is then provided to all docker containers.

Different docker containers may never share the same private/public key pairs.

We should think about using JSON (or a similar language) for config files, rather than a python script. The current solution allows executable code in the config file.
This allows us to read the config file only once, and then having a public Config object that provides relevant settings.
This is related to #1138

**Comment by t-gerhard** [comment]
I suggest doing this now, since this is a config syntax change, and we are working towards a new major release (4.0).

**Comment by dswd** [comment]
Ok. I suggest using YAML for config files. It is a superset of JSON and allows comments
