### ISSUE TITLE
Split Backend

### ISSUE THREAD

**Issue by t-gerhard** [GLab/ToMaTo#1162]
* backend_users (containing User objects)
 * useful API calls for checking Authentication and Authorization, editing and viewing users.
* backend_core
 * everything else

(remove line if done, mark line if working on it)
* [ ] Move Flags to backend_core
* [ ] enable mail functionality in backend_users
* [ ] iterating api calls like "send notifications to all users with [filter criteria]" in backend_users
* [ ] use backend_users by backend_core
* [ ] task which marks-read and deletes old notifications (in backend_users)
* [ ] move accounting functions from backend_users to backend_core
* [x] enable dumping on backend_users, register as dump source on backend_core dumpmanager
* [ ] enable logging for backend_users (or generic)

**Comment by dswd** [comment]
We need to handle the case where we check the permissions of users on topologies. Currently this involves checking the owners of the topology, users with global_topology_{owner, manager, user} flag and users of the same organization with global_topology_{owner, user, manager}
We need a way to calculate this without retrieving all data from the users service

**Comment by dswd** [comment]
Maybe a `users_list_names` api call that only returns the names and accepts filters for organization and flags.

**Comment by t-gerhard** [comment]
Maybe we should add an optional param to all ```info``` and ```list``` calls which allows to select columns. So we can basically do ```select (columns) from users where (filter-criteria like organization or site)```
