### ISSUE TITLE
Backend API connections test cases

### ISSUE THREAD

**Issue by swuest** [GLab/ToMaTo#1280]
### connection_create
- [x] Scenario 1: Correct parameters
- [x] Scenario 2: Correct parameters, without permission
- [x] Scenario 3: el1/el2 doesn't exist

### connection_modify
- [x] Scenario 1: Correct parameters
- [x] Scenario 2: Correct parameters, without permission
- [x] Scenario 3: Connection doesn't exist
- [x] Scenario 4: Incorrect attributes

### connection_action
- [x] Scenario 2: Non existing connection
- [x] Scenario 3: Non existing action

### connection_remove
- [x] Scenario 1: Correct parameter
- [x] Scenario 2: Correct parameter, without permission
- [x] Scenario 3: Non existing connection

### connection_info
- [x] Scenario 1: Correct parameter
- [x] Scenario 2: Correct parameter and fetch=True
- [x] Scenario 3: Non existing connection

### connection_usage
- [ ] Scenario 1: Correct parameter
- [ ] Scenario 2: Non existing connection

**Comment by t-gerhard** [comment]
Maybe element and connection should be tested in the same test module.
