### ISSUE TITLE
Backend API elements test cases

### ISSUE THREAD

**Issue by swuest** [GLab/ToMaTo#1282]
### element_create
- [x] Scenario 1: Correct parameters
- [x] Scenario 2: Correct parameters, without permission
- [x] Scenario 3: Create all existing technologies, start them and check for correctness.
- [x] Scenario 4: existing type in existing topology without parent and attributes
- [x] Scenario 5: not existing type and the other parameters correct
- [x] Scenario 6: correct parameters and incorrect attributes
- [x] Scenario 6.1: Non existing profile
- [x] Scenario 6.2: Non existing template
- [x] Scenario 7: existing type in non existing topology
- [x] Scenario 8: existing type and correct topology with non existing parent
- [x] Scenario 9: existing type and correct topology with existing parent, but parent is an interface
- [x] Scenario 10: existing type and correct topology with existing parent, but self is not an interface type
- [x] Scenario 11: existing type and correct topology with existing parent, but parent is in different topology

### element_modify
- [x] Scenario 1: Correct parameters
- [x] Scenario 2: Correct parameters, without permission
- [x] Scenario 3: Non existing element
- [x] Scenario 4: Non existing attribute
- [x] Scenario 5: Non existing template
- [x] Scenario 6: Non existing profile
- [x] Scenario 7: No permission for template
- [x] Scenario 8: No permission for profile

### element_remove
- [x] Scenario 1: Correct parameter
- [x] Scenario 2: Correct parameter, without permission
- [x] Scenario 3: Non existing element
- [x] Scenario 4: Remove element with child elements

### element_info
- [x] Documentation incomplete (fetch parameter)
- [x] Scenario 1: Correct parameter
- [x] Scenario 2: Non existing element
- [x] Scenario 3: Correct id and fetch=True (and child element)

### element_usage
- [x] Scenario 1: Correct parameter
- [x] Scenario 2: Non existing element

### host_remove (one scenario that should be best placed here)
- [x] Scenario 3: remove host with started element

**Comment by t-gerhard** [comment]
Maybe the template test cases that require templates to be synchronized should be done in the element test module
