### ISSUE TITLE
Backend API profile & templates test cases

### ISSUE THREAD

**Issue by swuest** [GLab/ToMaTo#1287]
## profile
- [x] Some parts of the documentation are incorrect 

### profile_list
- [x] Scenario 1: No parameters
- [x] Scenario 2: Set tech parameter to existing technology
- [x] Scenario 3: Set tech parameter to non existing technology

### profile_create
- [x] Scenario 1: Correct parameters
- [x] Scenario 2: Correct parameters, no permission
- [x] Scenario 3: Non existing techs, and otherwise corret parameters
- [x] Scenario 4: Already existing name (and same technology), but otherwise correct parameters
- [x] Scenario 5: Incorrect attributes

### profile_modify
- [x] Documentation corrected
- [x] Scenario 1: Correct parameters
- [x] Scenario 2: Correct parameters, no permission
- [x] Scenario 3: Non existing profile
- [x] Scenario 4: Incorrect attributes

### profile_remove
- [x] Documentation corrected
- [x] Scenario 1: Correct parameter
- [x] Scenario 2: Correct parameter, no permission
- [x] Scenario 3: Non existing profile

### profile_info
- [x] Documentation corrected
- [x] Scenario 1: Correct parameters
- [x] Scenario 2: Non existing id

### template_list
- [x] Scenario 1: No parameters
- [x] Scenario 2: Correct parameter
- [x] Scenario 3: Non existing technology

### template_create
- [x] Scenario 1: Correct parameters
- [x] Scenario 2: Correct parameters, without permission
- [x] Scenario 3: Non existing technology
- [x] Scenario 4: Already used name
- [x] Scenario 5: Incorrect attributes

### template_modify
- [x] Documentation corrected

- [x] Scenario 1: Correct parameters
- [x] Scenario 2: Correct parameters, without permission
- [x] Scenario 3: Non existing template
- [x] Scenario 4: Incorrect attributes

### template_remove
- [x] Documentation corrected

- [x] Scenario 1: Correct parameter
- [x] Scenario 2: Correct parameter, without permission
- [x] Scenario 3: Non existing template

### template_info
- [x] Documentation corrected

- [x] Scenario 1: Correct parameters
- [x] Scenario 3: Non existing template

**Comment by StephanSchlosser** [comment]
Removed torrent data test case
