### ISSUE TITLE
Standard archives as resources

### ISSUE THREAD

**Issue by t-gerhard** [GLab/ToMaTo#304]
The backend has resources of standard archives which have a url so the hostmanager can fetch them (see #303 ). The standard archives are hosted seperately!

attributes:
* name
* label
* description field
* url
* alternatives: {template_name:url}

The alternatives can be used to provide special archives for certain templates for better compatibility.

Next to enter an own upload url, the webfrontend provides a dropdown list to select from the standard archives.

**Comment by t-gerhard** [comment]
I am unsure whether we should do this via torrents.
torrent file structure:

* archive.tar.gz
* [template_name]
  * archive.tar.gz

(the template_name folders are for certain templates)
Using torrents would reduce traffic when using an archive.

@dswd what are your thoughts on this?

**Comment by dswd** [comment]
I am kind of undecided on this. I think we should handle this the same way as templates but I also don't like bittorrent in general. Bittorrent has some problems (opens lots of ports, needs a tracker, sometimes just hangs) and I want to get away from it. However I have not found a good alternative and therefore I think we should go with bittorrent.
