### ISSUE TITLE
Create a scripting tutorial in the wiki

### ISSUE THREAD

**Issue by dswd** [GLab/ToMaTo#656]
Contents:
* API usage
* Topology design (*_create, *_modify, *_remove)
* Topology control (*_action)
* Executing archives (https://gist.github.com/dswd/a7fc75483da406a47869)

**Comment by t-gerhard** [comment]
Started creating this: https://github.com/GLab/ToMaTo/wiki/APITutorial
Added an 'Understanding the API' section to APIUsage.
