### ISSUE TITLE
Websocket ports blocked by browsers

### ISSUE THREAD

**Issue by dswd** [GLab/ToMaTo#666]
Due to security considerations some browsers block some ports. There is no complete list of those ports but 6666 seems to be one of them.
`Uncaught SecurityError: Failed to execute 'connect' on 'WebSocket': The port 6666 is not allowed.`

Two solution ideas (we should implemenmt both):
- Maintain a blacklist of those port numbers and dont use them for websockets
- Create an action that restarts the VNS server of an element (and takes new random port numbers)

**Comment by dreyTee** [comment]
Met same issue while integrating noVNC. found these forbidden ports so far: 6000, 6665-6669, 6697
Tested official ports from wiki (https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers) manually (from 5900 to 10000).

Just to be sure: maybe someone knows full list of such forbidden_for_VNC ports?
