### ISSUE TITLE
Unstable sessions using the editor

### ISSUE THREAD

**Issue by swuest** [GLab/ToMaTo#940]
Sessions are very unstable while using the editor. This bug appears very often by using the editor.  @t-gerhard was able to repeat this error. We assume that performance problems in the webfrontend cause this problem on our local test servers.

**Comment by t-gerhard** [comment]
Sometimes, when the editor performs an API call, the error message "your session has ended, please log in again" appears. This error message then triggers a reload.
Sometimes, the reload redirects to the editor again, with the user logged in. Sometimes, it shows a login page, but the user is logged in (as indicated in the upper right corner). sometimes, it shows a "real" login page, but simply ignoring this and going to the topology list works fine (i.e., the user is then logged in again).
We haven't observed this outside the editor yet, but are unsure whether only the editor is affected, or the whole webfrontend. The editor does many API calls in parallel.

We have also observed this on master.tomato-lab.org.

**Comment by t-gerhard** [comment]
This was due to to many db connections on the backend. Has been fixed by adding semaphores or using a non-limited DB software.
