### ISSUE TITLE
Adblocker blocks UI elements

### ISSUE THREAD

**Issue by dswd** [GLab/ToMaTo#948]
In Firefox 35, the plugin Adblock plus seems to block the "connect" icon in the right-click menu of elements.

**Comment by swuest** [comment]
I reportet this problem to Adblock plus and hopefully will get an answer within the next days. 

This is a link to the ticket (the report is in german):

https://reports.adblockplus.org/cd7e6468-454d-4065-a324-be6f50362b63

**Comment by t-gerhard** [comment]
Has this been solved now?

**Comment by swuest** [comment]
I can't replicate it, it should be fixed. The ticket was deleted.
