### ISSUE TITLE
pretty-json-popup not working properly

### ISSUE THREAD

**Issue by t-gerhard** [GLab/ToMaTo#961]
This seems to have happened during the jquery update: the popup is not displayed correctly.
An example for this popup can be found in the dumpmanager, when you view the details of a dump. You can compare it to the current installation on master.
Maybe you should switch the two buttons.

**Comment by swuest** [comment]
I could not repeat this problem, maybe some caching problems?

**Comment by t-gerhard** [comment]
Now it's working. Maybe the js was cached in my browser or so.
