### ISSUE TITLE
django deprecation cycle

### ISSUE THREAD

**Issue by t-gerhard** [GLab/ToMaTo#969]
We had a few issues whenever there was a django update. we should pay attention to django's deprecation cycle (https://docs.djangoproject.com/en/1.8/internals/deprecation/#deprecation-removed-in-1-7)

* check whether we use any features that will be removed in the future
* switch to the alternatives if needed.

**Comment by dswd** [comment]
We can close this as the docker approach allows us to have the very same environment in development and production
