### ISSUE TITLE
NoReverseMatch for 'site_hosts' in tomato-web frontend

### ISSUE THREAD

**Issue by anmsid** [GLab/ToMaTo#970]
I added sites to an organization using tomato-cli. There was no problem when I only had one site. 
But when I added two more sites, I got this error when I view list of hosts on tomato-web (url: /host and /organization/name ).

The tomato-cli runs just fine, no error on both host_list() and site_list(). 
host_list('cl-clemson') returns the correct list of hosts on that site.
Also, there's no error in tomato-backend main.log

Notes:
I'm running tomato-backend 3.5.2 which is installed from ToMaTo Debian repo.
I've also tried github version of tomato-web

Error details:
Type: NoReverseMatch
Description: Reverse for 'site_hosts' with arguments '()' and keyword arguments '{'site': 'cl-clemson'}' not found.

/opt/ToMaTo/web/tomato/lib/__init__.py, line 108	in __call__
return self.fun(api, request, *args, **kwargs)
/opt/ToMaTo/web/tomato/admin/host.py, line 111	in list
return render(request, "host/list.html", {'host_list': hosts, 'organizations': organizations, 'site_map': site_map, 'sites': sites, 'site': site, 'site_description':site_description, 'organization': organization, 'organization_description': organization_description})
/usr/lib/python2.7/dist-packages/django/shortcuts/__init__.py, line 44	in render
return HttpResponse(loader.render_to_string(*args, **kwargs),
/usr/lib/python2.7/dist-packages/django/template/loader.py, line 176	in render_to_string
return t.render(context_instance)
/usr/lib/python2.7/dist-packages/django/template/base.py, line 140	in render
return self._render(context)
/usr/lib/python2.7/dist-packages/django/template/base.py, line 134	in _render
return self.nodelist.render(context)
/usr/lib/python2.7/dist-packages/django/template/base.py, line 823	in render
bit = self.render_node(node, context)
/usr/lib/python2.7/dist-packages/django/template/debug.py, line 74	in render_node
return node.render(context)
/usr/lib/python2.7/dist-packages/django/template/loader_tags.py, line 123	in render
return compiled_parent._render(context)
/usr/lib/python2.7/dist-packages/django/template/base.py, line 134	in _render
return self.nodelist.render(context)
/usr/lib/python2.7/dist-packages/django/template/base.py, line 823	in render
bit = self.render_node(node, context)
/usr/lib/python2.7/dist-packages/django/template/debug.py, line 74	in render_node
return node.render(context)
/usr/lib/python2.7/dist-packages/django/template/loader_tags.py, line 62	in render
result = block.nodelist.render(context)
/usr/lib/python2.7/dist-packages/django/template/base.py, line 823	in render
bit = self.render_node(node, context)
/usr/lib/python2.7/dist-packages/django/template/debug.py, line 74	in render_node
return node.render(context)
/usr/lib/python2.7/dist-packages/django/template/loader_tags.py, line 62	in render
result = block.nodelist.render(context)
/usr/lib/python2.7/dist-packages/django/template/base.py, line 823	in render
bit = self.render_node(node, context)
/usr/lib/python2.7/dist-packages/django/template/debug.py, line 74	in render_node
return node.render(context)
/usr/lib/python2.7/dist-packages/django/template/defaulttags.py, line 186	in render
nodelist.append(node.render(context))
/usr/lib/python2.7/dist-packages/django/template/defaulttags.py, line 426	in render
raise e

**Comment by t-gerhard** [comment]
This looks like a problem with the webfrontend. I'm invesigating it.

**Comment by t-gerhard** [comment]
The problem is that URLs expect only alphanumeric characters as names for sites, organizations, etc.
Thus, there is no URL for the site cl-clemson. As a temporary workaround, I suggest you delete the site and create a new one where the name does not contain non-alphanumeric characters.

We are going to fix this problem, but we might have to consider rules for site and organization names.

**Comment by t-gerhard** [comment]
Forget the temporary workaround, I just wrote a code that fixes this. Use this version of web/tomato/urls.py: https://github.com/t-gerhard/ToMaTo/blob/name_fix/web/tomato/urls.py
You should still avoid using the '/' character in names. In the future, the backend will not allow you to do this.

**Comment by anmsid** [comment]
Great! That fixed the problem. 
I was trying to map tomato sites name to cloudlab aggregates, they contain '-'  such as ig-uthaddc, cl-clemson, etc.

Thank you.
Asep
