### ISSUE TITLE
modify and create

### ISSUE THREAD

**Issue by t-gerhard** [GLab/ToMaTo#984]
when an element is created, this happens in two steps:
* create the element without any unneeded config (e.g., template description when creating a template)
* modify the element to add the unneeded config

if the second step fails, the user gets an error message, but the element is still created.
instead, the element should be deleted again.

**Comment by t-gerhard** [comment]
Also, input has been checked since the database throws weird errors on wrong input.
Should be done before the actual create, and also on modify API calls.

**Comment by dswd** [comment]
I think we got all cases fixed
